services:
  proxy:
    build: ./proxy
    ports:
      - "0.0.0.0:8080:80"
      - "0.0.0.0:8443:443"
    environment:
    - ALLOWLIST_IPS=${ALLOWLIST_IPS:-127.0.0.1 ::1 172.16.0.0/12 10.0.0.0/8 192.168.0.0/16}
#    - FRONTEND_ORIGIN=192.168.1.154:8443
    depends_on:
      frontend: { condition: service_started }
      gateway:  { condition: service_started }
    healthcheck:
      test: ["CMD-SHELL", "curl -kfsS https://localhost/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped


  frontend:
    build: ./frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -kfsS https://localhost/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  gateway:
    build: ./backend
    env_file: [.env]
    environment:
      - SERVICE_ROLE=gateway
      - PORT=8000
      - DB_PATH=${DB_PATH}
    volumes:
      - sqlite_data:/data
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:8000/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
    restart: unless-stopped


#--------------------------MICRO SERVICES BACKEND-----------------------------

  auth:
    build: ./backend
    environment:
      - SERVICE_ROLE=svc-auth
      - PORT=8101
    command: ["node", "dist/index.js"]
    expose: [ "8101" ]

  game:
    build: ./backend
    environment:
      - SERVICE_ROLE=svc-game
      - PORT=8102
    depends_on:
      - gateway
    expose: [ "8102" ]

  chat:
    build: ./backend
    environment:
      - SERVICE_ROLE=svc-chat
      - PORT=8103
    depends_on:
      - gateway
    expose: [ "8103" ]

  tournament:
    build: ./backend
    environment:
      - SERVICE_ROLE=svc-tournament
      - PORT=8104
    depends_on:
      - gateway
    expose: [ "8104" ]

  # CONTAINER TEST WS ET API
  visits:
    build: ./backend
    environment:
      - SERVICE_ROLE=svc-visits
      - PORT=8105
    depends_on:
      - gateway
    expose: [ "8105" ]




#--------------------------PROMETHEUS GRAFANA -------------------------

  prometheus:
    build: ./monitoring/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports: ["9090:9090"]
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped

  alertmanager:
    build: ./monitoring/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    ports: ["9093:9093"]
    volumes:
      - alertmanager-data:/alertmanager
    restart: unless-stopped

  grafana: 
    build: ./monitoring/grafana
    env_file: 
      - .env
    ports: ["3000:3000"]
    volumes:
      - grafana-data:/var/lib/grafana           # âœ… data persistante
    depends_on: [prometheus]
    restart: unless-stopped


#-----------------------ELK ----------------------------

  elasticsearch:
    build: ./monitoring/elk/elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.transport.ssl.enabled=false  
      - xpack.security.http.ssl.enabled=false      
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "-u", "elastic:elastic", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s"]
      interval: 10s
      timeout: 3s
      retries: 30

  kibana:
    build: ./monitoring/elk/kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "127.0.0.1:5601:5601"

  logstash:
    build: ./monitoring/elk/logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
    restart: unless-stopped

volumes:
  certs: {}
  grafana-data: {}
  prometheus-data: {}
  esdata: {}
  sqlite_data: {}
  alertmanager-data: {}
