services:
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      frontend:
        condition: service_started      
      gateway:
        condition: service_started
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/certs:/etc/nginx/certs:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost/healthz >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  frontend:
    build: ./frontend
    restart: unless-stopped
    healthcheck:
      #test: ["CMD-SHELL", "wget -q -O - http://localhost/ >/dev/null 2>&1 || exit 1"]
      test: ["CMD-SHELL", "curl -kfsS https://localhost/healthz >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  gateway:
    build: ./backend
    env_file: [.env]
    environment:
      - SERVICE_ROLE=gateway
      - PORT=8000
      - DB_PATH=${DB_PATH}
    volumes:
      - sqlite_data:/data
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:8000/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
    restart: unless-stopped


#--------------------------MICRO SERVICES BACKEND-----------------------------

  auth:
    build: ./backend
    env_file: [.env]
    environment:
      - SERVICE_ROLE=svc-auth
      - PORT=8101
      - DB_PATH=${DB_PATH}
    volumes: [ sqlite_data:/data ]
    expose: [ "8101" ]

  game:
    build: ./backend
    env_file: [.env]
    environment:
      - SERVICE_ROLE=svc-game
      - PORT=8102
      - DB_PATH=${DB_PATH}
    volumes: [ sqlite_data:/data ]
    expose: [ "8102" ]

  chat:
    build: ./backend
    env_file: [.env]
    environment:
      - SERVICE_ROLE=svc-chat
      - PORT=8103
      - DB_PATH=${DB_PATH}
    volumes: [ sqlite_data:/data ]
    expose: [ "8103" ]

  tournament:
    build: ./backend
    env_file: [.env]
    environment:
      - SERVICE_ROLE=svc-tournament
      - PORT=8104
      - DB_PATH=${DB_PATH}
    volumes: [ sqlite_data:/data ]
    expose: [ "8104" ]

  # CONTAINER TEST WS ET API
  visits:
    build: ./backend
    env_file: [.env]
    environment:
      - SERVICE_ROLE=svc-visits
      - PORT=8105
      - DB_PATH=${DB_PATH}
    volumes: [ sqlite_data:/data ]
    expose: [ "8105" ]




#--------------------------PROMETHEUS GRAFANA -------------------------

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/rules.yml:/etc/prometheus/rules.yml:ro
      - prometheus-data:/prometheus
    ports:
    - "9090:9090"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports: ["9093:9093"]
    restart: unless-stopped

  grafana: 
    image: grafana/grafana:11.1.4
    container_name: grafana
    env_file: 
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys:/sys:ro
    restart: unless-stopped

#-----------------------ELK ----------------------------

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.transport.ssl.enabled=false  
      - xpack.security.http.ssl.enabled=false      
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./monitoring/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "-u", "elastic:elastic", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s"]
      interval: 10s
      timeout: 3s
      retries: 30

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION:-8.14.0}
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=kibana_system
#      - ELASTICSEARCH_PASSWORD=kibana
    ports:
      - "127.0.0.1:5601:5601"
    volumes:
      - ./monitoring/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION:-8.14.0}
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
    volumes:
      - ./monitoring/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./monitoring/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro


volumes:
  certs: {}
  grafana-data: {}
  prometheus-data: {}
  esdata: {}
  sqlite_data: {}
